openapi: 3.0.2
# Revisions:
# 2019-05-09 initial version
# 2019-05-11 added nullable values to support patch
# 2019-05-17 TileRow and TileCol are now 'numbers' (not strings)
# 2019-05-17 "unless a different coordinate reference system is specified in the parameter `bbox-crs`." has been removed and instead we have added "unless a different coordinate         reference system is specified by another parameter in the API."
# 2019-05-21 "The default Tiling Scheme is the Google Maps Tiling Scheme" is changed to "The default Tiling Scheme is the WebMercatorQuad (sometimes refered as Google Maps Tiling Scheme)"
# 2019-05-21 "CRSId" has been added
#
info:
  title: OGC API Building Blocks
  description: |-
    Common components used in the OGC API maps and tiles standards.

    This document is also available in [GitHub](https://github.com/opengeospatial/OGC-API-Map-Tiles/tree/master/standard/openapi).

  version: "1.0.0"
  contact:
    name: Joan Maso
    email: joan.maso@uab.cat
  license:
    name: OGC License
    url: 'https://raw.githubusercontent.com/opengeospatial/OGC-API-Map-Tiles/master/LICENSE'

components:
  ####################
  # Common data models
  ####################
  schemas:
    ##########################################
    # From OGC API Common collections extended
    ##########################################
    collectionInfo:
      allOf:
      - $ref: 'https://raw.githubusercontent.com/opengeospatial/OGC-API-Map-Tiles/master/standard/openapi/ogc-api-maps.yaml#/components/schemas/style-set'
      - type: object
        properties:
          styles:
            $ref: 'https://raw.githubusercontent.com/opengeospatial/OGC-API-Map-Tiles/master/standard/openapi/ogc-api-maps.yaml#/components/schemas/style-set'
          mapCRSSetLink:
            $ref: 'https://raw.githubusercontent.com/opengeospatial/OGC-API-Map-Tiles/master/standard/openapi/ogc-api-maps.yaml#/components/schemas/mapCRSSetLink'
          tileMatrixSetLink:
            $ref: 'https://raw.githubusercontent.com/opengeospatial/OGC-API-Map-Tiles/master/standard/openapi/ogc-api-tiles.yaml#/components/schemas/tileMatrixSetLink-set'
          defaultStyle:
            type: string
            description: |-
              the style id of a recommended default style to use for this collection
            example: 'topographic'
    collectionInfo-patch:
      type: object
      properties:
        styles:
          $ref: 'https://raw.githubusercontent.com/opengeospatial/OGC-API-Map-Tiles/master/standard/openapi/ogc-api-maps.yaml#/components/schemas/style-set'
        defaultStyle:
          type: string
          nullable: true
          description: |-
            the style id of a recommended default style to use for this collection
          example: 'topographic'
  ####################
  # Common parameters
  ####################
  parameters:
    #############################
    # From OGC API Maps and Tiles
    #############################
    collections:
      name: collections
      in: query
      description: |-
        The collections that should be included in the response. The parameter value
        is a comma-separated list of collection identifiers.
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    infoCollections:
      name: infoCollections
      in: query
      description: |-
        The collections that are used in a response of a information request. The parameter value is a comma-separated list of collection identifiers.
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
    coord_i:
      name: i
      in: query
      description: |-
        Horizontal (x) coordinate within a map or tile.
      required: true
      style: form
      explode: false
      schema:
        type: number
    coord_j:
      name: j
      in: query
      description: |-
        Vertical (y) coordinate within a map or tile.
      required: true
      style: form
      explode: false
      schema:
        type: number
    infoTemplate:
      name: infoTemplate
      in: query
      description: |-
        template used for the information response. This parameter can be used to select among GML application schemas or JSON schemas and provide alternative presentations for the same information
      required: false
      style: form
      explode: false
      schema:
        type: number
    elevation:
      name: elevation
      in: query
      description: |-
        Elevation value
      required: false
      style: form
      explode: false
      schema:
        type: number

  #######################
  # Common request bodies
  #######################
  requestBodies: {}

  ####################
  # Common responses
  ####################
  responses:
    {}

  #########################
  # Common response headers
  #########################
  headers:
    {}

  #######################
  # Common path items
  # NOTE: Referencing pathitems does not seem to work, so I have stopped defining/using them
  #######################

  ######################################
  # Common examples of input/output data
  ######################################
  examples: {}

  #########################
  # Common link definitions
  #########################
  links: {}

  #########################
  # Common callback definitions
  #########################
  callbacks: {}
